In [567]:
import redis
import pymysql
import json
from datetime import datetime
import time
import random

In [568]:
config_redis = {'host': 'localhost',
                'port': 6379,
                'db': 0,}

config_mysql = {'host': 'localhost',
                'port': 3306,
                'user': 'root',
                'password': 'test',
                'db':'testdb'}

In [569]:
L = 40      # 起始溫度下限
U = 50      # 起始溫度上限
p = 0.2     # 溫度發生變化的機率
x = 2       # 溫度變化的異動範圍區間

In [570]:
pool_redis = redis.ConnectionPool(**config_redis)
r = redis.StrictRedis(connection_pool = pool_redis)

conn = pymysql.connect(**config_mysql)
cur = conn.cursor()
conn.autocommit(True)

In [571]:
def counter_data():
    global count
    
    count += random.randint(0, 5)
    
    pdDict = {'id': 'm1_s1',
              'dt':datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
              'v':count}
    print(pdDict)
    r.lpush('sensortype1', json.dumps(pdDict))
        
    sql = """INSERT INTO sensortype1 VALUES (%s, %s, %s)"""
    cur.execute(sql ,(pdDict['id'], pdDict['dt'], pdDict['v']))

In [572]:
def temperature():
    global tpt
    
    rnd = 0 if random.random() < (1 - p) else random.random() * x * 2 - x
    tpt = round(tpt + rnd, 2)

    pdDict = {'id': 'm1_s2',
              'dt':datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
              'tpt':tpt}
    print(pdDict)
    r.lpush('sensortype2', json.dumps(pdDict))
        
    sql = """INSERT INTO sensortype2 VALUES (%s, %s, %s)"""
    cur.execute(sql ,(pdDict['id'], pdDict['dt'], pdDict['tpt']))

In [573]:
count = 0
tpt = random.randint(L, U)

def produce():
    while True:
        counter_data()
        temperature()
        
        time.sleep(1)

In [574]:
produce()

{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:28:46', 'value': 3}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:28:47', 'tpt': 44}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:28:48', 'value': 7}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:28:49', 'tpt': 44}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:28:49', 'value': 10}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:28:49', 'tpt': 42.07}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:28:50', 'value': 12}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:28:50', 'tpt': 42.07}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:28:50', 'value': 17}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:28:50', 'tpt': 42.07}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:28:51', 'value': 21}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:28:51', 'tpt': 42.07}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:28:52', 'value': 21}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:28:52', 'tpt': 42.07}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:28:52', 'value': 21}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:28:52', 'tpt': 42.07}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:28:53', 'value': 25}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:28:53', 'tpt': 42.07}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:28:53', 'value': 29}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:28:53', 'tpt': 42.07}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:28:54', 'value': 31}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:28:54', 'tpt': 42.07}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:28:54', 'value': 34}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:28:54', 'tpt': 42.07}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:28:55', 'value': 37}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:28:55', 'tpt': 42.07}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:28:56', 'value': 38}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:28:56', 'tpt': 42.07}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:28:56', 'value': 38}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:28:56', 'tpt': 42.07}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:28:57', 'value': 40}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:28:57', 'tpt': 42.07}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:28:57', 'value': 45}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:28:57', 'tpt': 42.07}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:28:58', 'value': 47}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:28:58', 'tpt': 41.66}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:28:59', 'value': 52}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:28:59', 'tpt': 41.31}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:28:59', 'value': 53}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:00', 'tpt': 40.77}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:01', 'value': 53}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:01', 'tpt': 40.77}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:01', 'value': 53}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:02', 'tpt': 40.77}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:02', 'value': 55}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:02', 'tpt': 40.77}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:03', 'value': 60}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:03', 'tpt': 40.97}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:03', 'value': 61}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:03', 'tpt': 41.19}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:04', 'value': 63}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:04', 'tpt': 41.19}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:04', 'value': 66}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:04', 'tpt': 41.19}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:05', 'value': 66}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:05', 'tpt': 42.92}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:06', 'value': 71}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:06', 'tpt': 42.92}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:06', 'value': 71}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:06', 'tpt': 42.92}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:07', 'value': 72}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:07', 'tpt': 42.92}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:07', 'value': 73}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:07', 'tpt': 42.92}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:08', 'value': 76}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:08', 'tpt': 42.92}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:08', 'value': 79}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:08', 'tpt': 42.92}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:09', 'value': 82}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:09', 'tpt': 42.92}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:10', 'value': 82}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:10', 'tpt': 41.41}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:10', 'value': 87}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:10', 'tpt': 41.41}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:11', 'value': 90}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:11', 'tpt': 39.93}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:11', 'value': 94}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:11', 'tpt': 39.93}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:12', 'value': 97}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:12', 'tpt': 39.93}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:12', 'value': 99}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:12', 'tpt': 39.93}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:13', 'value': 99}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:13', 'tpt': 39.93}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:14', 'value': 104}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:14', 'tpt': 39.93}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:14', 'value': 105}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:14', 'tpt': 39.93}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:15', 'value': 110}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:15', 'tpt': 39.93}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:15', 'value': 115}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:15', 'tpt': 39.93}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:16', 'value': 115}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:16', 'tpt': 39.93}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:17', 'value': 120}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:17', 'tpt': 39.93}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:17', 'value': 125}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:17', 'tpt': 39.93}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:18', 'value': 128}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:18', 'tpt': 39.93}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:18', 'value': 130}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:18', 'tpt': 39.93}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:19', 'value': 132}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:19', 'tpt': 39.93}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:20', 'value': 135}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:20', 'tpt': 41.65}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:20', 'value': 136}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:20', 'tpt': 41.65}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:21', 'value': 140}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:21', 'tpt': 41.65}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:21', 'value': 144}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:21', 'tpt': 41.65}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:22', 'value': 144}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:22', 'tpt': 41.65}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:22', 'value': 148}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:22', 'tpt': 41.65}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:23', 'value': 151}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:23', 'tpt': 41.65}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:24', 'value': 154}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:24', 'tpt': 41.65}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:24', 'value': 157}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:24', 'tpt': 41.65}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:25', 'value': 161}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:25', 'tpt': 41.65}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:25', 'value': 162}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:25', 'tpt': 41.65}

{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:26', 'value': 163}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:26', 'tpt': 41.65}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:26', 'value': 166}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:26', 'tpt': 41.65}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:27', 'value': 171}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:27', 'tpt': 41.65}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:28', 'value': 175}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:28', 'tpt': 41.65}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:28', 'value': 176}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:28', 'tpt': 40.38}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:29', 'value': 176}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:29', 'tpt': 40.38}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:29', 'value': 180}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:29', 'tpt': 40.38}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:30', 'value': 183}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:30', 'tpt': 40.15}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:30', 'value': 183}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:31', 'tpt': 40.15}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:31', 'value': 185}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:31', 'tpt': 40.15}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:32', 'value': 186}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:32', 'tpt': 40.15}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:32', 'value': 191}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:32', 'tpt': 40.15}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:33', 'value': 194}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:33', 'tpt': 40.15}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:33', 'value': 196}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:33', 'tpt': 40.15}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:34', 'value': 197}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:34', 'tpt': 40.15}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:35', 'value': 198}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:35', 'tpt': 40.15}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:35', 'value': 199}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:35', 'tpt': 42.02}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:36', 'value': 201}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:36', 'tpt': 42.02}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:36', 'value': 206}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:36', 'tpt': 42.02}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:37', 'value': 209}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:37', 'tpt': 41.53}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:37', 'value': 214}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:37', 'tpt': 41.53}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:38', 'value': 218}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:38', 'tpt': 41.53}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:39', 'value': 222}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:39', 'tpt': 41.53}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:39', 'value': 227}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:39', 'tpt': 41.53}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:40', 'value': 229}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:40', 'tpt': 41.53}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:40', 'value': 233}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:40', 'tpt': 41.53}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:41', 'value': 238}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:41', 'tpt': 41.53}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:42', 'value': 240}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:42', 'tpt': 41.53}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:42', 'value': 244}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:42', 'tpt': 39.79}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:43', 'value': 245}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:43', 'tpt': 39.79}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:43', 'value': 249}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:43', 'tpt': 39.79}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:44', 'value': 254}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:44', 'tpt': 39.79}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:45', 'value': 258}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:46', 'tpt': 39.79}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:46', 'value': 259}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:46', 'tpt': 39.79}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:47', 'value': 264}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:47', 'tpt': 39.79}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:47', 'value': 265}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:47', 'tpt': 39.79}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:48', 'value': 270}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:48', 'tpt': 39.79}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:49', 'value': 274}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:49', 'tpt': 39.79}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:49', 'value': 279}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:49', 'tpt': 39.19}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:50', 'value': 280}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:50', 'tpt': 40.28}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:50', 'value': 282}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:50', 'tpt': 38.63}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:51', 'value': 287}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:51', 'tpt': 36.66}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:51', 'value': 289}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:52', 'tpt': 36.66}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:52', 'value': 293}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:52', 'tpt': 36.06}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:53', 'value': 297}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:53', 'tpt': 36.06}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:53', 'value': 299}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:53', 'tpt': 35.5}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:54', 'value': 302}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:54', 'tpt': 35.5}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:54', 'value': 302}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:54', 'tpt': 35.5}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:55', 'value': 306}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:55', 'tpt': 37.05}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:56', 'value': 310}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:56', 'tpt': 38.42}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:56', 'value': 315}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:56', 'tpt': 38.42}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:57', 'value': 319}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:57', 'tpt': 38.42}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:57', 'value': 322}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:57', 'tpt': 38.01}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:58', 'value': 322}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:58', 'tpt': 39.96}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:58', 'value': 325}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:58', 'tpt': 39.96}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:29:59', 'value': 326}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:29:59', 'tpt': 39.2}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:00', 'value': 330}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:00', 'tpt': 39.2}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:00', 'value': 330}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:00', 'tpt': 40.73}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:01', 'value': 331}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:01', 'tpt': 40.73}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:02', 'value': 334}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:02', 'tpt': 40.73}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:02', 'value': 337}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:02', 'tpt': 40.73}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:03', 'value': 339}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:03', 'tpt': 40.73}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:03', 'value': 339}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:03', 'tpt': 42.39}

{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:04', 'value': 341}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:04', 'tpt': 42.39}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:05', 'value': 346}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:05', 'tpt': 42.39}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:05', 'value': 350}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:06', 'tpt': 42.39}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:06', 'value': 352}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:06', 'tpt': 42.39}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:07', 'value': 353}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:07', 'tpt': 42.39}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:07', 'value': 354}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:07', 'tpt': 42.39}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:08', 'value': 358}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:08', 'tpt': 42.39}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:08', 'value': 363}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:08', 'tpt': 42.39}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:09', 'value': 367}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:09', 'tpt': 42.39}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:10', 'value': 367}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:10', 'tpt': 42.39}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:10', 'value': 371}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:10', 'tpt': 42.73}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:11', 'value': 376}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:11', 'tpt': 42.73}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:11', 'value': 379}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:11', 'tpt': 42.73}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:12', 'value': 379}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:12', 'tpt': 42.73}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:13', 'value': 380}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:13', 'tpt': 42.73}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:13', 'value': 382}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:13', 'tpt': 42.73}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:14', 'value': 383}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:14', 'tpt': 42.06}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:14', 'value': 384}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:14', 'tpt': 42.06}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:15', 'value': 384}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:15', 'tpt': 40.56}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:15', 'value': 388}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:16', 'tpt': 40.56}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:16', 'value': 391}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:16', 'tpt': 40.56}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:17', 'value': 395}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:17', 'tpt': 40.56}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:17', 'value': 399}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:17', 'tpt': 40.56}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:19', 'value': 400}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:19', 'tpt': 40.56}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:20', 'value': 405}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:20', 'tpt': 40.56}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:20', 'value': 407}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:20', 'tpt': 40.56}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:21', 'value': 412}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:21', 'tpt': 40.56}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:22', 'value': 414}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:22', 'tpt': 40.56}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:22', 'value': 418}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:22', 'tpt': 41.24}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:23', 'value': 418}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:23', 'tpt': 41.24}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:23', 'value': 422}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:23', 'tpt': 41.24}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:24', 'value': 427}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:24', 'tpt': 41.24}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:24', 'value': 427}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:24', 'tpt': 41.24}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:25', 'value': 431}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:25', 'tpt': 41.24}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:26', 'value': 431}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:26', 'tpt': 41.24}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:26', 'value': 431}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:26', 'tpt': 42.81}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:27', 'value': 434}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:27', 'tpt': 41.25}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:27', 'value': 434}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:27', 'tpt': 41.25}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:28', 'value': 439}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:28', 'tpt': 41.25}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:28', 'value': 444}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:29', 'tpt': 41.25}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:29', 'value': 445}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:29', 'tpt': 41.25}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:30', 'value': 449}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:30', 'tpt': 41.25}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:30', 'value': 454}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:30', 'tpt': 41.25}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:31', 'value': 457}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:31', 'tpt': 41.25}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:31', 'value': 460}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:31', 'tpt': 41.25}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:32', 'value': 462}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:32', 'tpt': 41.25}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:33', 'value': 466}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:33', 'tpt': 41.25}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:33', 'value': 471}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:33', 'tpt': 41.25}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:34', 'value': 471}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:34', 'tpt': 39.95}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:34', 'value': 473}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:34', 'tpt': 41.35}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:35', 'value': 473}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:35', 'tpt': 40.7}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:35', 'value': 475}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:35', 'tpt': 40.7}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:36', 'value': 476}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:36', 'tpt': 40.7}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:37', 'value': 479}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:37', 'tpt': 42.24}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:37', 'value': 481}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:37', 'tpt': 42.24}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:38', 'value': 485}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:38', 'tpt': 42.24}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:38', 'value': 488}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:38', 'tpt': 42.93}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:39', 'value': 493}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:39', 'tpt': 42.93}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:40', 'value': 497}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:40', 'tpt': 42.28}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:40', 'value': 502}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:40', 'tpt': 42.28}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:41', 'value': 504}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:41', 'tpt': 42.28}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:41', 'value': 508}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:41', 'tpt': 42.28}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:42', 'value': 510}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:42', 'tpt': 42.28}

{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:43', 'value': 512}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:43', 'tpt': 42.28}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:44', 'value': 514}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:44', 'tpt': 42.28}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:45', 'value': 518}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:45', 'tpt': 42.28}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:46', 'value': 520}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:47', 'tpt': 42.28}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:48', 'value': 522}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:48', 'tpt': 42.28}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:48', 'value': 526}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:48', 'tpt': 42.28}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:50', 'value': 530}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:50', 'tpt': 42.28}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:51', 'value': 531}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:51', 'tpt': 42.28}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:51', 'value': 531}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:51', 'tpt': 43.0}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:52', 'value': 532}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:52', 'tpt': 43.0}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:52', 'value': 537}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:54', 'tpt': 43.0}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:54', 'value': 541}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:56', 'tpt': 41.98}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:56', 'value': 544}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:56', 'tpt': 41.98}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:57', 'value': 544}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:58', 'tpt': 41.98}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:59', 'value': 546}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:59', 'tpt': 41.98}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:30:59', 'value': 550}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:30:59', 'tpt': 41.98}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:01', 'value': 550}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:01', 'tpt': 41.98}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:02', 'value': 553}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:02', 'tpt': 41.98}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:03', 'value': 554}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:03', 'tpt': 41.98}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:03', 'value': 557}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:03', 'tpt': 41.98}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:04', 'value': 559}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:04', 'tpt': 41.98}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:04', 'value': 559}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:04', 'tpt': 41.98}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:05', 'value': 564}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:05', 'tpt': 41.98}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:06', 'value': 565}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:06', 'tpt': 41.98}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:06', 'value': 569}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:06', 'tpt': 41.98}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:07', 'value': 574}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:07', 'tpt': 41.98}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:07', 'value': 576}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:07', 'tpt': 41.98}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:08', 'value': 578}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:08', 'tpt': 41.98}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:08', 'value': 580}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:09', 'tpt': 41.98}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:09', 'value': 585}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:09', 'tpt': 41.98}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:10', 'value': 588}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:10', 'tpt': 40.41}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:10', 'value': 592}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:12', 'tpt': 40.41}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:12', 'value': 597}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:12', 'tpt': 40.41}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:13', 'value': 597}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:13', 'tpt': 40.41}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:14', 'value': 599}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:14', 'tpt': 40.41}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:14', 'value': 602}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:14', 'tpt': 41.94}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:15', 'value': 602}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:15', 'tpt': 41.94}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:15', 'value': 606}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:15', 'tpt': 41.94}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:16', 'value': 607}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:16', 'tpt': 41.94}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:16', 'value': 608}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:16', 'tpt': 41.94}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:17', 'value': 613}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:17', 'tpt': 41.92}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:18', 'value': 614}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:18', 'tpt': 41.92}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:18', 'value': 618}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:18', 'tpt': 41.92}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:19', 'value': 619}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:19', 'tpt': 41.92}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:19', 'value': 624}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:19', 'tpt': 41.92}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:20', 'value': 629}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:20', 'tpt': 41.04}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:21', 'value': 631}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:21', 'tpt': 41.04}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:21', 'value': 632}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:21', 'tpt': 41.04}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:22', 'value': 635}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:22', 'tpt': 41.04}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:22', 'value': 637}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:22', 'tpt': 41.81}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:23', 'value': 638}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:23', 'tpt': 41.81}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:23', 'value': 643}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:24', 'tpt': 41.81}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:24', 'value': 647}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:24', 'tpt': 40.73}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:25', 'value': 648}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:25', 'tpt': 40.73}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:25', 'value': 648}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:25', 'tpt': 40.73}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:26', 'value': 648}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:26', 'tpt': 40.72}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:26', 'value': 652}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:26', 'tpt': 40.72}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:27', 'value': 654}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:27', 'tpt': 40.72}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:28', 'value': 658}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:28', 'tpt': 40.72}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:28', 'value': 659}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:28', 'tpt': 40.72}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:29', 'value': 659}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:29', 'tpt': 40.72}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:30', 'value': 661}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:30', 'tpt': 40.72}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:31', 'value': 665}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:31', 'tpt': 40.72}

{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:31', 'value': 668}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:31', 'tpt': 40.72}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:32', 'value': 673}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:32', 'tpt': 40.72}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:32', 'value': 673}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:32', 'tpt': 40.72}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:33', 'value': 674}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:33', 'tpt': 40.72}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:33', 'value': 675}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:33', 'tpt': 40.72}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:34', 'value': 675}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:34', 'tpt': 41.88}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:35', 'value': 679}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:35', 'tpt': 43.37}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:35', 'value': 683}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:35', 'tpt': 43.37}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:36', 'value': 684}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:36', 'tpt': 43.37}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:36', 'value': 687}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:36', 'tpt': 43.37}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:37', 'value': 688}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:37', 'tpt': 44.59}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:38', 'value': 691}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:38', 'tpt': 44.59}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:38', 'value': 693}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:38', 'tpt': 45.16}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:39', 'value': 698}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:39', 'tpt': 45.16}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:39', 'value': 698}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:39', 'tpt': 45.16}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:40', 'value': 699}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:40', 'tpt': 45.16}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:40', 'value': 699}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:40', 'tpt': 45.16}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:41', 'value': 704}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:41', 'tpt': 45.16}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:42', 'value': 709}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:42', 'tpt': 46.41}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:42', 'value': 710}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:42', 'tpt': 46.41}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:44', 'value': 711}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:44', 'tpt': 46.41}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:44', 'value': 715}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:44', 'tpt': 47.41}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:45', 'value': 715}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:45', 'tpt': 47.41}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:46', 'value': 719}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:46', 'tpt': 47.41}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:47', 'value': 724}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:47', 'tpt': 47.41}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:47', 'value': 728}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:47', 'tpt': 47.41}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:48', 'value': 730}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:48', 'tpt': 47.41}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:49', 'value': 735}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:49', 'tpt': 47.41}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:49', 'value': 736}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:50', 'tpt': 47.41}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:50', 'value': 736}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:51', 'tpt': 47.41}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:52', 'value': 738}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:54', 'tpt': 47.85}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:54', 'value': 742}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:54', 'tpt': 47.85}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:55', 'value': 747}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:56', 'tpt': 47.33}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:56', 'value': 749}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:56', 'tpt': 47.33}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:57', 'value': 752}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:57', 'tpt': 47.33}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:58', 'value': 752}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:58', 'tpt': 47.33}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:59', 'value': 754}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:31:59', 'tpt': 47.33}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:31:59', 'value': 759}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:32:00', 'tpt': 47.33}
{'m_id': 1, 's_id': 1, 'dt': '2018-05-23 16:32:00', 'value': 764}
{'m_id': 1, 's_id': 2, 'dt': '2018-05-23 16:32:00', 'tpt': 47.33}

KeyboardInterrupt:

In [575]:
def consumer(i):
    while r.llen('sensortype1') > i:
        r.rpop('sensortype1')
    
    while r.llen('sensortype2') > i:
        r.rpop('sensortype2')

In [576]:
data_range = 50
consumer(data_range)